language: node_js

node_js:
  - '10.16.0'

sudo: false

# Add your branch here to have it tested and deployed
branches:
  only:
    - master

before_install:
  # Configure Git
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"

  # Get all tags of git repo
  - git fetch origin 'refs/tags/*:refs/tags/*'

script:
  - test "$TRAVIS_PULL_REQUEST" == "false" || npm run build:prod:fast
  - test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || npm run build:prod

before_deploy:
  # Set environment variables for Elastic Beanstalk deploy
  - echo 'origin.proofi.com' > dist/CNAME
  - export TAG=$(git tag --contains)

deploy:
  - provider: pages
    local_dir: dist/
    skip_cleanup: true
    github_token:
      secure: dTEKv2PUHA2LwlhkCtCUOWPq0qq8Z7ojLAXLt1ggQoC5efakzkw+fSoLlg+HqPdyrjq4MOF1sWmwaEjxB6o4ApwwrmE/XjD8Lb2GkQPwyQzVUa5saxMf1xMzobRZpddhvUXe1yiY+oEXe40/ud0uMWI5AqUduUCiOlobMJzCJSSDCbzdAuOfjtcdKIF5REpZAvsgTzNtxYVZVjSr8vDzqZFU9eyYYPdwTq1jE70V0t+P8k7DVJutXYk2nyVp8z7XyB/MRbsEc68sFGSnhckJzI6Xxbj7swNvi66Q+B8vxBeqlzWIu1V7KvnsoBBvhdkfDdZAr5DJdTax9zm7jwt2EN3fz+QuKXFm53N1P+IyI63hHT9fj+llxJ2inQnPe7a7Lh7alMwdPAjZBmTPg3devirhdPae46WGtXhnfgVk002c4toHFC4sUBaGLYh3JFu7Niu2ELo1dSC01MxN4Q4P3ogHfUosQbhAbDJAlMAQ1NCfarCYA7b+zGLc3rsYar1i8vs3/J46UCRHYtUwgH5yLCndMjMNbYFBVO94e4y77t1l3RpPn89b4dIszC5AkGtzXEQ2ezLdNgTLrqGLhZGb8eD/8GI8BkJfmYMykb9ukOvnSIMqUy0vMD/25+ZgT6WwB2SSy3cD869FgjgugHUuOCZz0sBQTNUCaFqsLrjRhJk=
    keep_history: true
    on:
      branch: master
